name: Deploy ASP.NET Core app to Azure Web App 

on:
  push:
    branches:
      - master

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_CREDENTIALS
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: "netcorestartertest"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'             # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.302'                  # set this to the dot net version to use
  RESOURCEGROUPNAME: "netcorestartertest-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "netcorestartertest-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}