name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: "netcorestartertest"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'             # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.302'                  # set this to the dot net version to use
  RESOURCEGROUPNAME: "{{inputs.resourceGroup}}"
  LOCATION: "{{inputs.location}}"
  HOSTINGPLANNAME: "{{inputs.webAppName}}-plan"
  APPINSIGHTLOCATION: "{{inputs.appInsightLocation}}"
  SKU: "{{inputs.appServicePlan}}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          cd Application
          dotnet restore
          dotnet build --configuration Release
          dotnet test
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Application' 