name: Deploy ASP.NET Core app to Azure Web App 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repo
    - uses: actions/checkout@master
    
    - name: testing script
      run: |
        SCOPE="incremental"
          REF="${{ github.base_ref }}"
          echo $REF
          if [[ ${{ github.ref }} =~ ^refs/heads/(main|patch/|ci-test/).* ]]; then
             SCOPE="all"
             REF="${{ github.ref_name }}"
          fi
          echo "Executing: .github/workflows/go/ci.sh -t ut -S \"$SCOPE\" -r \"$REF\""
          .github/workflows/go/ci.sh -t ut -S "$SCOPE" -r "$REF" -b "$BRANCH"
